version: '3'
services:
    database:
        image: 'mongo'
        container_name: 'rcommerce-express-mongo-contaianer'
        environment:
            - MONGO_INITDB_DATABASE=rcommerce-express-mongo-db
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        volumes:
            - D://docker_data//mongo_config//init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - D:\docker_data\mongo_data_rcommerce_express:/data/dbn
        ports:
            - '27017:27017'